### ISSUE TITLE
No output on no/wrong commands

### ISSUE THREAD

**Issue by vmx** [hugomrdias/connect-deps#8]
The CLI doesn't display anything when used without arguments. I suggest it displays the help by default. It also doesn't display anything if non existent commands are used.

It's probably the command line parser. I've had a good experience with https://github.com/felixSchl/neodoc. I've e.g. used it here: https://github.com/vmx/dagbuilder/blob/master/src/bin.js.

**Comment by vmx** [comment]
`cli.js link` without any arguments still doesn't print out anything.

**Comment by hugomrdias** [comment]
now should be fixed

**Comment by vmx** [comment]
It's still happening. Run `./cli.js link` on a fresh checkout and there won't be any output.
